### ISSUE TITLE
当使用相同的KEY，上传文件问题

### ISSUE THREAD

**Issue by charryxiaoyu** [qiniu/java-sdk#141]
当使用相同的KEY，上次文件的时候 
如果 我设置了scope为bucket:key 为这种模式的时候 7牛服务端 报 bad token

如果 我设置 scope为bucket为这种模式的时候  7牛服务端 报  File already exist 

这个问题困扰很久了，希望能及时回复

**Comment by longbai** [comment]
麻烦 给个具体的示例，scope 为 bucket时，如果已有 同名文件不能覆盖

**Comment by charryxiaoyu** [comment]
这种方式 KEY 值相同 会报 File already exist
public Object createToken(FileModel record,Boolean openCallBack ) throws Exception {
    	
		Config.ACCESS_KEY = AppConfig.getInstance().getQiniuAccessKey();
		Config.SECRET_KEY = AppConfig.getInstance().getQiniuSecretKey();
		mac = new Mac(Config.ACCESS_KEY, Config.SECRET_KEY);
		AppConfig.getInstance().setQiniuBucketName(record.getBucketType());
		putPolicy = new PutPolicy(AppConfig.getInstance().getQiniuBucketName());
		putPolicy.saveKey = createSaveKey(record);
		putPolicy.callbackUrl=createCallbackUrl(record.getOpenCallBack());
		putPolicy.callbackBody=createCallbackBody(record);
		putPolicy.returnBody=createReturnBody(record);
		uptoken = putPolicy.token(mac);
		TokenModel obj=new TokenModel();
		obj.setUptoken(uptoken);
		return obj;
	}

这种方式 KEY 值相同  bad token
public Object createToken(FileModel record,Boolean openCallBack ) throws Exception {
    	
		Config.ACCESS_KEY = AppConfig.getInstance().getQiniuAccessKey();
		Config.SECRET_KEY = AppConfig.getInstance().getQiniuSecretKey();
		mac = new Mac(Config.ACCESS_KEY, Config.SECRET_KEY);
		AppConfig.getInstance().setQiniuBucketName(record.getBucketType());
                //假如我上传test.png  key 也是test.png
		putPolicy = new PutPolicy(AppConfig.getInstance().getQiniuBucketName()+":test.png");
		putPolicy.saveKey = createSaveKey(record);
		putPolicy.callbackUrl=createCallbackUrl(record.getOpenCallBack());
		putPolicy.callbackBody=createCallbackBody(record);
		putPolicy.returnBody=createReturnBody(record);
		uptoken = putPolicy.token(mac);
		TokenModel obj=new TokenModel();
		obj.setUptoken(uptoken);
		return obj;
	}

**Comment by forrest-mao** [comment]
上传策略初始化的时候使用 `putPolicy = new PutPolicy(AppConfig.getInstance().getQiniuBucketName());`是不能覆盖上传的，同名文件上传会返回`614 file exists`；如果使用 `putPolicy = new PutPolicy(AppConfig.getInstance().getQiniuBucketName()+":test.png");` 进行初始化，那么需要在put函数或者putFile函数中，将key参数也设置为`test.png`才能进行覆盖上传。

**Comment by charryxiaoyu** [comment]
我这边只是用到7牛 JAVA-SDK 生成TOKEN返回给客户端，客户端直接上传到7牛的方式，
而是不客户端上传到我这边的业务服务器上，然后用7牛 JAVA-SDK上传到7牛云服务器上。
我这边不会用到put函数或者putFile函数来上传

**Comment by forrest-mao** [comment]
@charryxiaoyu 了解，七牛默认不支持覆盖上传，如果上传需要覆盖，需要设置上传策略(http://developer.qiniu.com/docs/v6/api/reference/security/put-policy.html)中的scope参数为"bucketname:key"，而设置scope参数在javaSDK中就是通过上传策略初始化的时候`putPolicy = new PutPolicy("bucketname:key");`，然后这么生成的上传凭证，传给客户端进行上传，就可以进行覆盖上传操作。

**Comment by charryxiaoyu** [comment]
问题已经解决，需要覆盖上传的话
1设置scope参数在javaSDK中就是通过上传策略初始化的时候`putPolicy = new PutPolicy("bucketname:key") 
2 必须在客户端指定key值 这个key 必须跟new PutPolicy("bucketname:key") 的key 相同才能 完成覆盖
