### ISSUE TITLE
官网文档链接有错

### ISSUE THREAD

**Issue by normalJaylan** [qiniu/java-sdk#194]
http://developer.qiniu.com/code/v7/sdk/java.html       JavaSDK文档中 SDK 的下载链接存在错误

![image](https://cloud.githubusercontent.com/assets/13521880/14319273/1fbbc4f2-fc43-11e5-9713-d372fdea6639.png)

http://search.maven.org/##search%7Cgav%7C1%7Cg%3A%22com.qiniu%22%20AND%20a%3A%22qiniu-java-sdk%22      此链接中search前多了一个#符号，导致无法显示正常结果

**Comment by longbai** [comment]
收到，我们改下

**Comment by longbai** [comment]
👍 👍 👍  我们已经改好了，十分感谢
