### ISSUE TITLE
使用java删除七牛文件异常

### ISSUE THREAD

**Issue by dmxiaoshen** [qiniu/java-sdk#197]
java.lang.IncompatibleClassChangeError: Found class com.squareup.okhttp.Connection, but interface was expected

jdk环境1.7+

jar包依赖：
```

<dependency>
 <groupId>com.qiniu</groupId>
 <artifactId>qiniu-java-sdk</artifactId>
 <version>[7.0.0, 7.0.99]</version>
</dependency>
	     
<dependency>
  <groupId>com.squareup.okhttp</groupId>
  <artifactId>okhttp</artifactId>
  <version>2.7.5</version>			 
</dependency>
		
<dependency>		
  <groupId>com.squareup.okio</groupId>
  <artifactId>okio</artifactId>
  <version>1.6.0</version>
</dependency>

```

请问到底什么版本的okhttp和okio是可以正常使用的?

**Comment by longbai** [comment]
我们看下，这个类应该是没有直接用到的

**Comment by sxci** [comment]
com.qiniu:qiniu-java-sdk:7.1.+ 

工具可以解决其自身的依赖，不用再单独配置其它依赖项。
若和其它jar依赖冲突，需要测试。

**Comment by clouddxy** [comment]
您好，7.0.8需要okhttp 2.6.0版本的支持，您将okhttp和okio换成这一下两个jar包再试下:
okhttp: 2.7.0
http://7xkn2v.dl1.z0.glb.clouddn.com/okhttp-2.7.0.jar
okio: 1.6.0
http://7xkn2v.dl1.z0.glb.clouddn.com/okio-1.6.0.jar

**Comment by dmxiaoshen** [comment]
多谢楼上各位，问题已经解决，原因大概是项目中pom文件一些传递依赖导致实际用的 okhttp:2.4.0  okio:1.4.0   qiniu-java-jdk:7.0.8  而出问题，经过测试（单独弄一个工程） 像问题开始那样的配置依赖是没问题的。

问题出在maven中的pom.xml依赖管理和继承。
