### ISSUE TITLE
可否给出上传进度的回调？

### ISSUE THREAD

**Issue by axeon** [qiniu/java-sdk#203]
可否给出上传进度的回调？
另外，也可以在回调中提供终止上传的办法。

**Comment by longbai** [comment]
能描述下需要的场景么？ android 有这个功能，服务端基本都是后台运行，基本用不到。

**Comment by axeon** [comment]
我们服务器和客户端都用一个库。。。
没有用android的sdk是因为不想再引入一套东西了。

另外一点，我认为在web上传的时候，或许也有一定的意义。

**Comment by longbai** [comment]
web上传一般建议用js直接上传到七牛。 我们看下。
