### ISSUE TITLE
可否给出ResumeUploader的Demo

### ISSUE THREAD

**Issue by zhanghao1013** [qiniu/java-sdk#216]
看了下ResumeUploader的源码，对于参与 定义 有些不是很明白，能给ResumeUploader的Demo么？

**Comment by longbai** [comment]
根据文件大小自动选择是否采用resume uploader, 您直接传file 就行

**Comment by zhanghao1013** [comment]
程序自动选择？？UploadManager  只是建立一次连接 。 连接超时、或者意外终端的话 连接就断了 。文件自动断点续传？
