### ISSUE TITLE
关于“回调通知callback”的问题

### ISSUE THREAD

**Issue by cjie** [qiniu/java-sdk#222]
1. 如果客户端使用标准SDK，那么业务服务器处理回调通知后的返回消息格式有什么要求？  
官网在线文档说明中给的示例是返回：`{"success":true,"name":"sunflowerb.jpg"}`,然而github上的`关于回调流程.md`说明示例给的是`{"response": "success"}`。由于这个返回消息会透传给客户端，那么这个格式是否有要求？
2. 服务端进行回调接口安全验证时，建议JAVA SDK中提供方法进行安全验证，这个是通用需求；  
目前Java SDK中还缺少回调安全验证、响应返回的完整使用示例，还不够友好，第一次开发时还有一定难度。

**Comment by peaceful321** [comment]
1.返回的消息格式主要是标准的json，而且这个json是可以自定义的，通过callbackBody来指定，语法格式：key=$(key)&eTag=$(etag)&w=$(imageInfo.width)&h=$(imageInfo.height) ；这个在七牛开发者中心的“上传策略”中有做文档说明，链接：http://developer.qiniu.com/article/developer/security/put-policy.html。
2.安全校验其实可以在回调url中加一个自定义参数来验证该参数的值，根据该值来校验是否走正常流程；然后完整使用示例会在做好后发到七牛的开发者中心
