### ISSUE TITLE
不同块的并发上传

### ISSUE THREAD

**Issue by wanghaisheng** [qiniu/java-sdk#223]
文档中讲“分片上传过程中每个块内部只能按顺序逐一上传该块所切分好的片。而每个块之间相互独立，因此若干个块可以同时进行传输而不会相互干扰，因此我们可以利用这个特征实现并发上传特性。”
可否给一个例子 谢谢

**Comment by liuchengjason** [comment]
Hi,
https://github.com/qiniu/api.v7
http://developer.qiniu.com/code/v7/sdk/go.html

**Comment by wanghaisheng** [comment]
@liuchengjason 您给的这些都是普通常见的分片/分块上传的示例 
我是想问“并发上传” 比如说并发上传数量的限制

**Comment by longbai** [comment]
@wanghaisheng 数量不做限制，但不建议特别多
