### ISSUE TITLE
有没有考虑去除 okhttp，gson 的依赖

### ISSUE THREAD

**Issue by fengyapeng** [qiniu/java-sdk#224]
有没有考虑过去除对okhttp 的依赖，gson 的依赖。
java 中有httpclient，okhttp，URLConnect 等很多第三方可以请求和解析的http 类的包，json 的世界也是很多：jackson1，2，fastjson，gson 等很多~
不知道是否可以选择性的使用http 组件和json 组件呢

**Comment by longbai** [comment]
这个依赖倒不是很强，已经对第三方做了封装，将来改成从外部设置也可以做到。不过话又说回来，服务端不用考虑安装包大小问题，在sdk内部使用这些，不影响外面的程序。

**Comment by longbai** [comment]
另外 增加额外的依赖 如果出现bug 也会比较头大，不好定位。
