### ISSUE TITLE
Why my Qiniu SDK have no Json.class

### ISSUE THREAD

**Issue by chenzhaoyan** [qiniu/java-sdk#240]
public String uploadTokenWithDeadline(String bucket, String key, long deadline, StringMap policy, boolean strict) {
        // TODO   UpHosts Global
        String scope = bucket;
        if (key != null) {
            scope = bucket + ":" + key;
        }
        StringMap x = new StringMap();
        copyPolicy(x, policy, strict);
        x.put("scope", scope);
        x.put("deadline", deadline);

        String s = Json.encode(x);
        return signWithData(StringUtils.utf8Bytes(s));
    }

    public String uploadTokenWithPolicy(Object obj) {
        String s = Json.encode(obj);
        return signWithData(StringUtils.utf8Bytes(s));
    }

**Comment by longbai** [comment]
https://github.com/qiniu/java-sdk/blob/master/src/main/java/com/qiniu/util/Json.java 在这里
