### ISSUE TITLE
改进对异常的处理

### ISSUE THREAD

**Issue by akuma** [qiniu/java-sdk#255]
看到不少代码里面捕获异常后都是直接输出到控制台的，建议使用 logger 来处理。

**Comment by jemygraw** [comment]
嗯，这个在计划中。

**Comment by akuma** [comment]
赞！建议编码用比较通用的 logger 接口 slf4j，这样方便使用者选择不同的 logger 实现，比如 logback/log4j/log4j2 等等。

**Comment by jemygraw** [comment]
目前是测试代码输出exception到终端，sdk代码没有，这个暂时可以关闭。
