### ISSUE TITLE
改进对 final class 的处理

### ISSUE THREAD

**Issue by alswl** [qiniu/java-sdk#259]
我司长期使用 7.0.3 版本。在一些 TestCase 里面，需要 mock 一些类，比如 `OperationManager` 。
然而新版本 `7.1.2` 将这类 Manager 设置为 `final`，作为一个 Library，将 Service 类型设置为 final，虽然保证了外部无法进行修改，但是也同时关上一扇门。后果是之一是导致无法 mock 进行单元测试，甚为遗憾。

能否考虑一下用户的这类场景，将 final class 去掉？

**Comment by alswl** [comment]
有一个比较难以接受的是 v7.2.3 的 `Constants` 的配置完全 final 锁死，导致无法进行调整。
比如 `WRITE_TIMEOUT = 0` 的设置，在 Remote server 响应异常情况下，会出现将线程全部消耗完的情况。

**Comment by jemygraw** [comment]
新版本可以通过Configuration类来自定义相关的变量，Constants里面的是默认的。

**Comment by jemygraw** [comment]
OperationManager的构造函数里面有Configuration，可以通过构建Configuration对象来实现OperationManager的不同可定制行为。
