### ISSUE TITLE
Client 连接池大小和并发限制是否可配置

### ISSUE THREAD

**Issue by songjiayang** [qiniu/java-sdk#273]
查看了代码，发现 Client 的连接池大小是写死的，并发不够大, 是否可配置呢？

https://github.com/qiniu/java-sdk/blob/123ea8020ef8b4a1e287bf789ba3a76ae9ed9f91/src/main/java/com/qiniu/http/Client.java#L45-L47

```java
        dispatcher.setMaxRequests(64);
        dispatcher.setMaxRequestsPerHost(16);
        ConnectionPool connectionPool = new ConnectionPool(32, 5, TimeUnit.MINUTES);
```

**Comment by jemygraw** [comment]
Fixed in ce09f591d77395d0f2297b721d37472e06e6508e
