### ISSUE TITLE
java.lang.NoClassDefFoundError: okhttp3/Interceptor

### ISSUE THREAD

**Issue by gxlcl** [qiniu/java-sdk#292]
7.0.x 版本的jdk 6.0 不能直接使用mvn上的okhttp, 需要另外下载，代码, okhttp.jar, okio.jar 7.1.x, 7.2.x 版本 jdk6.0 支持 后面会做处理，暂时只支持7及以上, 原因同前。

这段话不太理解， jdk7 环境下 okhttp.jar okio.jar 到底需要什么版本？

**Comment by liuchengjason** [comment]
您好，jdk7可以下载3.2以上版本的okhttp 和1.6版本的okio的jar包
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.squareup.okhttp3%22

上面那段话是指6.0版本的jdk对okhttp和okio支持有些问题，所以建议使用7.0版本的jdk。

**Comment by gxlcl** [comment]
thanks @liuchengjason 

其实 https://developer.qiniu.com/kodo/sdk/java 这里的maven dependency 说明的比较清楚，怪我前面没好好看。。。。
<dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <version>3.3.1</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.6.2</version>
      <scope>compile</scope>
    </dependency>
