### ISSUE TITLE
fetch的接口会出现等待很长时间么

### ISSUE THREAD

**Issue by dmxiaoshen** [qiniu/java-sdk#296]
线上环境有调用七牛fetch接口，但是出现调用超过10s钟才有响应，无报错。现在想弄清楚，有哪些场景下，七牛的这个fetch接口调用会花费这么长时间？个人猜测，网络，或者bucket空间锁住等等，但是这都只是臆想，想请官方给分析下。

**Comment by KevinChenQiniu** [comment]
请问 fetch 的文件有多大？可以把具体的文件 url 和操作的时间提交个工单到七牛，我们来查一查。

**Comment by dmxiaoshen** [comment]
大概700k，但是我单元测试连续跑几百次调用都不超过1s，基本稳定在300毫秒以内，线上补上了这个方法的执行时间日志，下次出现的话再定位一下。（目前怀疑是业务内其他方法引起超时）

**Comment by jemygraw** [comment]
fetch时间过长一般和你需要fetch的url的响应速度有关系，也有可能是对方服务器不让fetch。
