### ISSUE TITLE
七牛fetch文件图片存储类型问题

### ISSUE THREAD

**Issue by dmxiaoshen** [qiniu/java-sdk#304]
七牛的fetch接口传送的参数url，如果是jpg的图片，bucket里面存储类型是application/octet-stream（为什么不是image/jpeg），而png的图片，bucket里面存储类型是image/png。这样导致一个问题，传参数key（七牛唯一文件标识）的时候，如果直接用uuid，同样是谷歌浏览器，jpg的打开则默认下载，png的打开则页面展示图片。

**Comment by jemygraw** [comment]
麻烦给个图片地址看下。
