### ISSUE TITLE
私有空间，文件下载，设置过期时间无效

### ISSUE THREAD

**Issue by whisky1234** [qiniu/java-sdk#305]
文件上传到私有空间之后，由本地生成访问url连接，设置了过期时间，为什么已经过了失效时间，访问链接地址还能访问该资源呢？

**Comment by jemygraw** [comment]
这个目前和cdn的域名有关系，可以把域名的缓存时间修改短一点，以后会处理的。不过一般不建议用私有空间，可以用公开空间+时间戳防盗链来实现权限控制。
