### ISSUE TITLE
zone的新园区适配问题、autozone异常问题

### ISSUE THREAD

**Issue by kitmanzheng** [qiniu/java-sdk#323]
1、你们上了新zone，我们用了之前的sdk，想使新的zone就得更新sdk然后重新发布？
2、使用了autozone之后，可能我这网络不太好，经常抛connect timeout的异常，但是我指定一个zone，就不会出现。

**Comment by hktry** [comment]
1：是的，但是即使更新的Zone，直接的sdk版本中Zone对应的的上传域名依然是可以使用的
2：autozone会发起网络请求去获取上传域名，直接指定Zone就不需要，所以建议直接指定对应的zone进行上传

**Comment by kitmanzheng** [comment]
第一个问题不考虑解决？客户需要不停的跟进服务商sdk，是不合理的。
