### ISSUE TITLE
IntelliJ IDEA Maven 获取不到 qiniu-java-sdk:7.2.11

### ISSUE THREAD

**Issue by JamesZBL** [qiniu/java-sdk#325]
IntelliJ IDEA Maven 获取不到 qiniu-java-sdk:7.2.11

**Comment by jemygraw** [comment]
http://search.maven.org/#artifactdetails%7Ccom.qiniu%7Cqiniu-java-sdk%7C7.2.11%7Cjar
这个已经发布了，一般idea会有点问题，多试试
