### ISSUE TITLE
私有域下载链接不对

### ISSUE THREAD

**Issue by sjlian** [qiniu/java-sdk#326]
1.问题描述：
 完全按照sdk生成的私有域下载链接，返回401，且download token not specified。
2.问题分析过程：
在七牛控制台上操作，点击下载，然后获取到的下载链接和代码生成的链接不一致。
这是测试代码：
        String fileName = "从七牛控制台复制的文件名";
        String domainOfBucket = "从七牛控制台复制的域名";
        String encodedFileName = URLEncoder.encode(fileName, "utf-8");
        String publicUrl = String.format("%s/%s", domainOfBucket, encodedFileName);
        String accessKey = "xxxxxxx";
        String secretKey = "xxxxxx";
        Auth auth = Auth.create(accessKey, secretKey);
        long expireInSeconds = 3600;//1小时，可以自定义链接过期时间
        String finalUrl = auth.privateDownloadUrl(publicUrl, expireInSeconds);
        System.out.println(finalUrl);
得到的finalUrl是（401错误）：http://(mydomain).bkt.clouddn.com/(myfile)?e=1523503596&token=H4h2uEFDh3NDASUbn7gYU5p4Vmy5KIdJF7rcnL-4:EWeHozNKKcLcFM9ukZXXetDkxSk=
从控制台的链接（是可以下载和访问的）：http://(mydomain).bkt.clouddn.com/(myfile)?attname=&e=1523505781&token=H4h2uEFDh3NDASUbn7gYU5p4Vmy5KIdJF7rcnL-4:91UQpygMj64_KoYycoe3ZIm8cRQ

**Comment by jemygraw** [comment]
这个最好给下代码（ak，sk不需要填）

**Comment by sjlian** [comment]
下面是关键代码：
public class QiniuService {
   //以下是通过配置文件进行配置的，获取token，上传，以及公有链接下载都是没有问题的，说明配置无问题。且token过期时间设置了6小时，但实际只要查出来就是401。
    @Value("${qiniu.accessKey}")
    private String accessKey;
    @Value("${qiniu.secretKey}")
    private String secretKey;
    @Value("${qiniu.callbackUrl}")
    private String callbackUrl;
    @Value("${qiniu.private.expireSeconds}")
    private Long expireSeconds;
    @Value("${qiniu.env.test}")
    private boolean test;

    //密钥配置
    private Auth auth;
    //创建上传对象
    private UploadManager uploadManager;

    @PostConstruct
    public void  init(){
        //密钥配置
        auth = Auth.create(accessKey, secretKey);
        //要上传的空间(bucket)的存储区域为华北时
        Zone z = Zone.autoZone();
        Configuration c = new Configuration(z);
        //创建上传对象
        uploadManager = new UploadManager(c);
    }

    //获取基础下载链接地址
    private String getBaseUrl(String bucketName,String key){
        return String.format("%s/%s", getBucketDomain(bucketName,test), key);
    }

   // 获取私有链下载地址
   private String getPrivateDownloadUrl(String bucketName, String key) {
        String baseUrl = getBaseUrl(bucketName, key);
        return auth.privateDownloadUrl(baseUrl, expireSeconds);
    }

   //这个是根据bucket获取domain的方法，内容略。公有链是对的，说明这个没问题。
   private String getBucketDomain(String bucketName,boolean test) {

   }
}

**Comment by jemygraw** [comment]
```
 @Test
    public void testPrivateUrl() {
        String domain = "http://if-pri.qiniudn.com";
        String ak = "ak";
        String sk = "sk";
        Auth auth = Auth.create(ak, sk);
        String baseUrl = domain + "/qiniu.png";
        String privateUrl = auth.privateDownloadUrl(baseUrl, 3600);
        System.out.println(privateUrl);
    }
```
我用上面的代码测试是OK的，你要不看看是domain还是baseUrl哪里有问题吧。或者是ak，sk不对，或是ak，sk和domain不是一个账号下面的。
