### ISSUE TITLE
java 8 环境下使用github提供的okhttp-2.3.0-SNAPSHOT，报错NoClassDefFoundError，麻烦给一个确定的依赖版本

### ISSUE THREAD

**Issue by Charles-Xiao** [qiniu/java-sdk#350]
java.lang.NoClassDefFoundError: okhttp3/RequestBody
        at com.qiniu.storage.BucketManager.<init>(BucketManager.java:51) ~[server.jar:0.9.3]

依赖版本：
okhttp-2.3.0-SNAPSHOT.jar
okio-1.3.0-SNAPSHOT.jar

**Comment by forrest-mao** [comment]
java 1.8 以上的 jdk 可以用 okhttp 3.14.2 及以上的版本，okio 用最新版本即可（2.7以上版本）

**Comment by forrest-mao** [comment]
详细版本依赖可以参考文档 https://developer.qiniu.com/kodo/sdk/1239/java
