### ISSUE TITLE
如何使用java-sdk校验配置是否正确？

### ISSUE THREAD

**Issue by daxiong294** [qiniu/java-sdk#353]
如何校验配置的七牛相关参数（如：accessKey、secretKey、bucket、个人资源下载地址等）是否有效或者正确？

**Comment by daxiong294** [comment]
使用java-sdk时出现这个错误：javax.net.ssl.SSLPeerUnverifiedException: Hostname uc.qbox.me not verified:

**Comment by litianqi1996** [comment]
可以提交下详细信息到七牛工单平台 
https://support.qiniu.com/
