### ISSUE TITLE
checkAsynFetchid无法查询，返回400

### ISSUE THREAD

**Issue by huminted** [qiniu/java-sdk#364]
checkAsynFetchid方法中的fetchWorkId  是response.reqId吗
`Response response;
            Response response2;
            response=bucketManager.asynFetch(remoteSrcUrl, bucket, key);
            System.out.println( response);
            System.out.println( response.duration+response.reqId+response.address);

            do {
                response2 =  bucketManager.checkAsynFetchid("z2",response.reqId);
                System.out.println( response2.duration);

            }while (!response2.isOK());`

**Comment by forrest-mao** [comment]
fetchWorkId 不是 response.reqId，是 asyncFetch 方法响应的 body 中的 id 字段。

**Comment by blyen** [comment]
怎么知道抓取完毕，一直都是{"id":"eyJ6b25lIjoiejIiLCJxdWV1ZSI6InBlcnNpc3RlbnQ6Ly9rb2RvL3Npc3lwaHVzL2ZldGNoIiwicGFydF9pZCI6LTEsIm9mZnNldCI6LTEsIm1pZCI6IjEyMDYzMTo0ODY6MTAifQ==","wait":-1}

**Comment by YangSen-qn** [comment]
> 怎么知道抓取完毕，一直都是{"id":"eyJ6b25lIjoiejIiLCJxdWV1ZSI6InBlcnNpc3RlbnQ6Ly9rb2RvL3Npc3lwaHVzL2ZldGNoIiwicGFydF9pZCI6LTEsIm9mZnNldCI6LTEsIm1pZCI6IjEyMDYzMTo0ODY6MTAifQ==","wait":-1}

可以直接查询相应的 文件是否已经保存在目标的 Bucket 中。
