### ISSUE TITLE
SDK对于中文名称的文件名没有做编码转换，在 OKHTTP 3.12.0 版本下无法通过 OKHTTP 的编码检查，导致中文名称的文件无法上传成功

### ISSUE THREAD

**Issue by yanxiangqun** [qiniu/java-sdk#403]
OKHTTP 3.12.0 新版本相比旧版本，增加了在添加 header 时候强制检查 value 编码类型的逻辑；

我们使用的七牛上传SDK，在添加上传中文名称文件的时候，分片POST场景下由于SDK没有做 filename 的编码转换，会导致 无法通过 OKHTTP 编码， 无法成功发起上传请求；

**Comment by forrest-mao** [comment]
#447 这个 pr 中已经修复

**Comment by forrest-mao** [comment]
#447 中已经修复
