### ISSUE TITLE
没有autoZone()方法了？

### ISSUE THREAD

**Issue by dannyxu2015** [qiniu/java-sdk#428]
java sdk，版本：7.2.18
`
private static final Configuration CONFIGURATION = new Configuration(Zone.autoZone());
`
gradle运行springboot项目时出错：
The following method did not exist:

    com.qiniu.common.Zone.autoZone()Lcom/qiniu/common/Region

**Comment by dannyxu2015** [comment]
gradle里改为指定7.2.18后就不会出错了，原来写的是”7.2.+“

**Comment by sxci** [comment]
fixed.
