### ISSUE TITLE
方法 uploadManager.put(uploadBytes, key, upToken); 建议改造一下

### ISSUE THREAD

**Issue by xunkoo** [qiniu/java-sdk#483]
put方法的 upToken 和 Auth 耦合了

**Auth auth = Auth.create(accessKey, secretKey);
String upToken = auth.uploadToken(bucket);**
uploadManager.put(uploadBytes, key, upToken); 

建议改造成用 uploadManager 的构造方法 或者 用Configuration 注入 accessKey, secretKey,bucket  .否则把配置写在业务代码里太糟糕了！

特别是整合Spring的时候不能优雅的编码太难受了！！
![image](https://user-images.githubusercontent.com/67527425/86445907-c395f800-bd45-11ea-8a18-6af7ba668ae3.png)

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-988

**Comment by peteryuanpan** [comment]
您好
1）请问目前accessKey、secretKey、bucket参数是放在SpringBoot配置文件application.yml或者application.properties中吗？
2）您目前希望的配置与业务解耦合，方便给个具体的示例吗？这边没有非常明白您的含义，感谢

**Comment by xunkoo** [comment]
> 您好
> 1）请问当前访问密钥，秘密密钥，存储桶参数是放在SpringBoot配置文件application.yml或者application.properties中吗？
> 2）您当前希望的配置与业务解散，方便给一个具体的示例吗？这边没有非常明白您的含义，感谢


---------------------------------------------------------------------

抱歉！
比如在 UploadManager 的类中构造一个方法 UploadManager(String accessKey ,  String secretKey , String bucket),
把需要的配置字段通过构造传入 且 预留一个token字段 等待赋值，
如果这个构造方法被调用就去生成token ，这样对接的时候管理单例的UploadManager  Bean就行了，而不是每次调用都去创建一个新的对象、反复请求生成token ：

```java
public UploadManager(String accessKey ,  String secretKey , String bucket) {
        super(appId, apiKey, secretKey); //父类实现也可以
    }

///////////////////////////////////////////////////////

public abstract class XxxxSuper{
     ....
     protected XxxxSuper.Auth.create token;

     protected XxxxSuper(String appId, String apiKey, String secretKey) {
             this.accessKey = accessKey ;
             this.secretKey = secretKey ;
             this.bucket= bucket;
             ...
             this.token= new Auth.create();
     }

     public static Auth create(String accessKey, String secretKey) {
            if (!StringUtils.isNullOrEmpty(accessKey) && !StringUtils.isNullOrEmpty(secretKey)) {
                byte[] sk = StringUtils.utf8Bytes(secretKey);
                SecretKeySpec secretKeySpec = new SecretKeySpec(sk, "HmacSHA1");
                return new Auth(accessKey, secretKeySpec);
            } else {
                throw new IllegalArgumentException("empty key");
            }
       }
}
```

**Comment by xunkoo** [comment]
目前我是这样注入spring的
![image](https://user-images.githubusercontent.com/67527425/88382945-16f6e580-cddc-11ea-9f36-76fb10939fde.png)
![image](https://user-images.githubusercontent.com/67527425/88382952-1cecc680-cddc-11ea-808d-025d0b9ec2fc.png)

**Comment by Rorke76753** [comment]
我感觉可以这么写
```java
@Component
public class Util {
    @Value("${qiniu-cloud.accessKey}")
    private String qiniucloudAccessKey;

    @Value("${qiniu-cloud.secretKey}")
    private String qiniucloudSecretKey;

    @Value("${qiniu-cloud.bucket}")
    private String qiniucloudBucket;
}
```

**Comment by peteryuanpan** [comment]
不好意思，回复晚了

有几个问题与您沟通一下

1、您上面的回复，期望构造方法被调用去生成token，而不是每次调用都去创建一个反复请求生成token，这是不太合规的。原因有：一，token有过期时间，二，可能由于上传文件名或上传策略不同，需要多次生成token

2、希望不要每次调用都去创建一个新的对象，是指UploadManager对象还是Auth对象？
对于Auth对象，是支持只生成一次，申明为static的
对于UploadManager对象或其他对象，您看下业务上是否有办法不要频繁生成，我理解这一点与1是不冲突

有回复不到位的地方欢迎您指出，这边再为您解答

**Comment by xunkoo** [comment]
好吧！
