### ISSUE TITLE
7.2.29版本没有打tag

### ISSUE THREAD

**Issue by wsy** [qiniu/java-sdk#491]
![tag list](https://user-images.githubusercontent.com/2684991/90881227-5ebd5c80-e3dc-11ea-821d-844d99de7c80.png)
如图，只有7.2.28以及之前的

**Comment by peteryuanpan** [comment]
您好，7.2.29已经release
https://github.com/qiniu/java-sdk/tags
https://github.com/qiniu/java-sdk/releases
