### ISSUE TITLE
云短信BadToken

### ISSUE THREAD

**Issue by q757571446** [qiniu/java-sdk#498]
![image](https://user-images.githubusercontent.com/13860006/94637203-8d96ee80-0309-11eb-9bba-3c5aaf727cb7.png)

**Comment by forrest-mao** [comment]
从报错来看，是 token 错误，一般原因是在初始化鉴权密钥的时候出现异常导致的，您可以参考 https://github.com/qiniu/java-sdk/blob/master/examples/SendMessageDemo.java 这个 demo，检查下是否密钥对位置填写的内容和账号中密钥对保持一致 https://portal.qiniu.com/user/key

**Comment by q757571446** [comment]
> 从报错来看，是 token 错误，一般原因是在初始化鉴权密钥的时候出现异常导致的，您可以参考 https://github.com/qiniu/java-sdk/blob/master/examples/SendMessageDemo.java 这个 demo，检查下是否密钥对位置填写的内容和账号中密钥对保持一致 https://portal.qiniu.com/user/key

本地运行正常发送短信，发布到阿里云出现BadToken错误。我换一个Access/Secret Key试试

**Comment by forrest-mao** [comment]
好的，您更换密钥对测试之后帮忙也同步下效果

**Comment by q757571446** [comment]
> 好的，您更换密钥对测试之后帮忙也同步下效果

问题依然存在，我拷贝了SmsManager代码，增加了日志打印。
![image](https://user-images.githubusercontent.com/13860006/94639463-ce453680-030e-11eb-887b-41236939afb3.png)
![image](https://user-images.githubusercontent.com/13860006/94639491-db622580-030e-11eb-95dc-348475919bc9.png)

**Comment by q757571446** [comment]
> 好的，您更换密钥对测试之后帮忙也同步下效果

发送失败请求消息头: {"Authorization":"Qiniu -s900t_572Mz3VtN4eM_okyEzpMjz7n5ObbFAALG:PGrs6gB8LgI_UfnXHYqA9WV4G6Y\u003d"}
发送成功请求消息头:{"Authorization":"Qiniu -s900t_572Mz3VtN4eM_okyEzpMjz7n5ObbFAALG:imQX2nAqj2K0Pqxsq1h9-APhzh0\u003d"}
另外有没有可能是发送内容的编码问题造成的，如果有可能我检查下查询出来的中文编码格式是否正确

**Comment by forrest-mao** [comment]
目前看比较像是body 的编码问题，因为签算 token 的时候会带上 body 一起签名和校验，如果编码存在问题，可能会导致我们服务端校验 token 失败，您看是否需要将编码转换为 utf-8 的编码，一般不会有问题

**Comment by q757571446** [comment]
> 目前看比较像是body 的编码问题，因为签算 token 的时候会带上 body 一起签名和校验，如果编码存在问题，可能会导致我们服务端校验 token 失败，您看是否需要将编码转换为 utf-8 的编码，一般不会有问题

感谢，问题已解决，jar包启动是指定编码-Dfile.encoding=UTF-8，就能够发送成功

**Comment by forrest-mao** [comment]
麻烦了
