### ISSUE TITLE
下载方法在哪啊

### ISSUE THREAD

**Issue by panicknight** [qiniu/java-sdk#506]

**Comment by panicknight** [comment]
我按照文档中http://<domain>/<key>?e=<deadline>&token=<downloadToken>，
auth.privateDownloadUrl,使用SDK中的auth生成downloadurl,把<domain>修改成私有的下载链接，后面拼上文件key，再加上
downloadurl，结果报错{"error":"no such domain"}

**Comment by panicknight** [comment]
li

**Comment by ACANX** [comment]
@panicknight 貌似要用  https://developer.qiniu.com/kodo/manual/4093/s3-authentication.md 这个方法签名

<img width="1936" height="907" alt="Image" src="https://github.com/user-attachments/assets/ec4ab972-1128-4430-9d92-efbcf2a8b442" />
