### ISSUE TITLE
Zone.Builder方法过时

### ISSUE THREAD

**Issue by GabbyMrH** [qiniu/java-sdk#521]
![image](https://user-images.githubusercontent.com/30254530/118451798-3161cd00-b728-11eb-999c-6c40e334d351.png)
如上图所示，这个方法既然过时了，为什么官网SDK说明还在用这个方法？建议更新。版本号为:7.5

**Comment by YangSen-qn** [comment]
感谢您的反馈

**Comment by Mei-Zhao** [comment]
对外文档已更新 https://developer.qiniu.com/kodo/1239/java
