### ISSUE TITLE
If you can add JavaDoc to this project?

### ISSUE THREAD

**Issue by Kicey** [qiniu/java-sdk#565]
The absent of the JavaDoc make the sdk hard to use!
e.g. I want to know the meaning of `Auth`, I found it's no way. You don't provide it anywhere!
I don't expect you to provide a complete reference, only JavaDoc, please! To see what [minio sdk](https://github.com/minio/minio-java) did!

**Comment by Kicey** [comment]
e.g. How can I know if `Auth` object cacheable? Search in SE?

**Comment by YangSen-qn** [comment]
Thank you for your feedback.  and now you can view source code comments according to your needs.
