### ISSUE TITLE
maven找到七牛云的jar包

### ISSUE THREAD

**Issue by KenoChou** [qiniu/java-sdk#589]
maven作为我使用的java构建工具，此刻确无法jar包，我该何去何从？望告知！
![image](https://github.com/qiniu/java-sdk/assets/75463608/9817f0bc-9183-4900-9bc5-ac83b13bfb42)

**Comment by bachue** [comment]
建议使用 Maven 的 [Central Repository](https://mvnrepository.com/repos/central)，aliyun 的 maven 不是我们的发布渠道。

**Comment by KenoChou** [comment]
谢谢，名字打错了qiniu打成qiuniu了发自我的手机-------- 原始邮件 --------发件人： Bachue Zhou ***@***.***>日期： 2023年9月26日周二 09:53收件人： qiniu/java-sdk ***@***.***>抄送： Keno Chou ***@***.***>, Author ***@***.***>主    题： Re: [qiniu/java-sdk] maven找到七牛云的jar包 (Issue #589)
建议使用 Maven 的 Central Repository，aliyun 的 maven 不是我们的发布渠道。

**Comment by KenoChou** [comment]
谢谢，名字打错了qiniu打成qiuniu了
